language: php

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - '7.2'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

notifications:
  email: false
  on_success: never
  on_failure: always

git:
  depth: 1

install:
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - composer check-code
